"""edit int to string2

Revision ID: 03424fa5aea2
Revises: d43460267987
Create Date: 2019-03-10 17:22:37.288728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03424fa5aea2'
down_revision = 'd43460267987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('mobile', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'mobile')
    # ### end Alembic commands ###
