"""second build

Revision ID: 7f45060ba099
Revises: 42f4e165aee1
Create Date: 2018-12-28 17:42:33.440830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f45060ba099'
down_revision = '42f4e165aee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_file', sa.Column('file_folder', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_file', 'file_folder')
    # ### end Alembic commands ###
