"""user

Revision ID: ac5572153680
Revises: c4f38fbbc381
Create Date: 2019-03-06 18:04:11.997917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac5572153680'
down_revision = 'c4f38fbbc381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('password', sa.String(length=16), nullable=False))
    op.drop_column('user_info', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('password_hash', mysql.VARCHAR(length=16), nullable=False))
    op.drop_column('user_info', 'password')
    # ### end Alembic commands ###
