"""user

Revision ID: c4f38fbbc381
Revises: 94f5e31e32e2
Create Date: 2019-03-06 17:50:14.891708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4f38fbbc381'
down_revision = '94f5e31e32e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('password_hash', sa.String(length=16), nullable=False))
    op.drop_column('user_info', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('password', mysql.VARCHAR(length=16), nullable=False))
    op.drop_column('user_info', 'password_hash')
    # ### end Alembic commands ###
