"""add superlink_info

Revision ID: ffbe927c937b
Revises: 7f45060ba099
Create Date: 2019-03-03 15:37:55.939884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbe927c937b'
down_revision = '7f45060ba099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_superlink',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_name', sa.String(length=32), nullable=False),
    sa.Column('link_url', sa.Text(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_superlink')
    # ### end Alembic commands ###
